Models/Province.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarRent.Models
{
    public class Province
    {
        [Key]
        [Display(Name = "Province")]
        public int ProvinceId { get; set; }

        [Required]
        [Display(Name = "Province Name")]
        [MaxLength(50)]
        [MinLength(2, ErrorMessage = "Province name must contain at least two characters.")]
        public string ProvinceName { get; set; }

        public int CountryId { get; set; }

        [ForeignKey("CountryId")]
        public Country Country { get; set; }

        public ICollection<District> Districts { get; set; }
    }
}

Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRent.Data;
using CarRent.Models;

namespace CarRent.Controllers
{
    public class CountryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CountryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Country
        public async Task<IActionResult> Index()
        {
            return View(await _context.Countries.ToListAsync());
        }

        // GET: Country/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Country/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountryId,CountryName")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Country/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Country/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CountryId,CountryName")] Country country)
        {
            if (id != country.CountryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.CountryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Country/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .FirstOrDefaultAsync(m => m.CountryId == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _context.Countries.FindAsync(id);
            _context.Countries.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(int id)
        {
            return _context.Countries.Any(e => e.CountryId == id);
        }
    }
}

Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRent.Data;
using CarRent.Models;

namespace CarRent.Controllers
{
    public class ProvinceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProvinceController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Province
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Provinces.Include(p => p.Country);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Province/Create
        public IActionResult Create()
        {
            ViewData["CountryId"] = new SelectList(_context.Countries, "CountryId", "CountryName");
            return View();
        }

        // POST: Province/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProvinceId,ProvinceName,CountryId")] Province province)
        {
            if (ModelState.IsValid)
            {
                _context.Add(province);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "CountryId", "CountryName", province.CountryId);
            return View(province);
        }

        // GET: Province/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var province = await _context.Provinces.FindAsync(id);
            if (province == null)
            {
                return NotFound();
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "CountryId", "CountryName", province.CountryId);
            return View(province);
        }

        // POST: Province/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProvinceId,ProvinceName,CountryId")] Province province)
        {
            if (id != province.ProvinceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(province);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProvinceExists(province.ProvinceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "CountryId", "CountryName", province.CountryId);
            return View(province);
        }

        // GET: Province/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var province = await _context.Provinces
                .Include(p => p.Country)
                .FirstOrDefaultAsync(m => m.ProvinceId == id);
            if (province == null)
            {
                return NotFound();
            }

            return View(province);
        }

        // POST: Province/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var province = await _context.Provinces.FindAsync(id);
            _context.Provinces.Remove(province);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProvinceExists(int id)
        {
            return _context.Provinces.Any(e => e.ProvinceId == id);
        }
    }
}

Views/Province/Create.cshtml
@model CarRent.Models.Province

@{
    ViewData["Title"] = Localizer["Add A Province"];
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px" id="contact-section">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="Index" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="row">
            <div class="col-lg-8 mb-5">
                <form asp-action="Create" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <div class="col-md-12 mb-4 mb-lg-0">
                            <label asp-for="ProvinceName" class="control-label"></label>
                            <input asp-for="ProvinceName" class="form-control" />
                            <span asp-validation-for="ProvinceName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12 mb-4 mb-lg-0">
                            <label asp-for="CountryId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Country" class="btn btn-primary float-right">@Localizer["Add a new country"]</a>
                            <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mr-auto">
                            <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5" value="@Localizer["Add"]">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Province/Delete.cshtml
@model CarRent.Models.Province

@{
    ViewData["Title"] = "Delete The Province";
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@Localizer["Delete"] @Model.ProvinceName</h2>
                <h3>@Localizer["Are you sure you want to delete this?"]</h3>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="Index" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="item-1">
                <div class="item-1-contents">
                    <div class="text-center">
                        <h3>@Model.ProvinceName</h3>
                    </div>
                    <ul class="specs">
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.ProvinceId)</span>
                            <span class="spec spec2">@Model.ProvinceId</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.Country.CountryName)</span>
                            <span class="spec spec2">@Model.Country.CountryName</span>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="ProvinceId" />
            <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
        </form>
    </div>
</div>

Views/Province/Edit.cshtml
@model CarRent.Models.Province

@{
    ViewData["Title"] = "Edit The Province";
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px" id="contact-section">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="Index" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="row">
            <div class="col-lg-8 mb-5">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ProvinceId" />
                    <div class="form-group row">
                        <div class="col-md-12 mb-4 mb-lg-0">
                            <label asp-for="ProvinceName" class="control-label"></label>
                            <input asp-for="ProvinceName" class="form-control" />
                            <span asp-validation-for="ProvinceName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12 mb-4 mb-lg-0">
                            <label asp-for="CountryId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Country" class="btn btn-primary float-right">@Localizer["Add a new country"]</a>
                            <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mr-auto">
                            <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5" value="@Localizer["Update"]">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 ml-auto">
                <div class="bg-white p-3 p-md-5">
                    <h3 class="text-black mb-4">@Localizer["Current Values"]</h3>
                    <ul class="list-unstyled footer-link">
                        <li class="d-block mb-3">
                            <span class="d-block text-black">@Html.DisplayNameFor(model => model.ProvinceId)</span>
                            <span>@Model.ProvinceId</span>
                        </li>
                        <li class="d-block mb-3">
                            <span class="d-block text-black">@Html.DisplayNameFor(model => model.ProvinceName)</span>
                            <span>@Model.ProvinceName</span>
                        </li>
                        <li class="d-block mb-3"><span class="d-block text-black">@Html.DisplayNameFor(model => model.Country.CountryName) </span><span>@Model.Country.CountryName</span></li>
</div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Province/Index.cshtml
@model IEnumerable<CarRent.Models.Province>

@{
    ViewData["Title"] = "List All Provinces";
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="Create" class="btn btn-primary">@Localizer["Add new province"]</a>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="item-1">
                        <div class="item-1-contents">
                            <div class="text-center">
                                <h3>@item.ProvinceName</h3>
                            </div>
                            <ul class="specs">
                                <li>
                                    <span class="spec2">@Html.DisplayNameFor(model => model.ProvinceId)</span>
                                    <span class="spec spec2">@item.ProvinceId</span>
                                </li>
                                <li>
                                    <span class="spec2">@Html.DisplayNameFor(model => model.Country.CountryName)</span>
                                    <span class="spec spec2">@item.Country.CountryName</span>
                                </li>
                            </ul>
                            <div class="d-flex action">
                                <a asp-action="Edit" asp-route-id="@item.ProvinceId" class="btn btn-primary mr-2">@Localizer["Edit"]</a>
                                <a asp-action="Delete" asp-route-id="@item.ProvinceId" class="btn btn-primary">@Localizer["Delete"]</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>