Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace CarRent.Models
{
    public class Car
    {
        [Key]
        [Display(Name = "Car")]
        public int CarId { get; set; }
        
        [Required]
        [Display(Name = "Brand")]
        public string CarBrand { get; set; }

        [Required]
        [Display(Name = "Model")]
        public string CarModel { get; set; }

        [Required]
        [Display(Name = "Type")]
        public CarType CarType { get; set; }

        [Required]
        [Display(Name = "Trim Package")]
        public string CarTrimPackage { get; set; }

        [Required]
        [Display(Name = "Color")]
        public string CarColor { get; set; }

        [Required]
        [Display(Name = "Product Year")]
        [Range(1970, 10000)]
        public int CarProductYear { get; set; }

        [Required]
        [Display(Name = "Kilometer")]
        [Range(0, int.MaxValue)]
        public int CarKilometer { get; set; }

        [Required]
        [Display(Name = "Rent Price")]
        [Range(0, double.MaxValue)]
        public double CarRentPrice { get; set; }

        [Required]
        [Display(Name = "Deposit")]
        [Range(0, double.MaxValue)]
        public double CarDepositPrice { get; set; }

        [Required]
        [Display(Name = "Minimum Age")]
        [Range(0, int.MaxValue)]
        public int MinimumAge { get; set; }

        public string CarImageUrl { get; set; }

        public string CarCoverImageUrl { get; set; }

        [Required]
        [Display(Name = "Transmission")]
        public CarTransmissionType CarTransmissionType { get; set; }

        public int EngineId { get; set; }

        public int OfficeId { get; set; }

        [ForeignKey("EngineId")]
        public Engine Engine { get; set; }

        [ForeignKey("OfficeId")]
        public Office Office { get; set; }

        public ICollection<Reservation> Reservations { get; set; }
    }

    public enum CarType
    {
        Sedan,
        HatchBack,
        Coupe,
        Station,
        Suv,
        Minivan,
        SportsCar
    }

    public enum CarTransmissionType
    {
        [Display(Name = "Manual")]
        Manual,
        [Display(Name = "Automatic")]
        Automatic,
        [Display(Name = "Semi Automatic")]
        Semi
    }
}

Controllers/EngineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRent.Data;
using CarRent.Models;

namespace CarRent.Controllers
{
    public class EngineController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EngineController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Engine
        public async Task<IActionResult> Index()
        {
            return View(await _context.Engines.ToListAsync());
        }

        // GET: Engine/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Engine/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EngineId,EngineName,EngineHorsePower,EngineVolume,EngineFuelType")] Engine engine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(engine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(engine);
        }

        // GET: Engine/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var engine = await _context.Engines.FindAsync(id);
            if (engine == null)
            {
                return NotFound();
            }
            return View(engine);
        }

        // POST: Engine/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EngineId,EngineName,EngineHorsePower,EngineVolume,EngineFuelType")] Engine engine)
        {
            if (id != engine.EngineId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(engine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EngineExists(engine.EngineId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(engine);
        }

        // GET: Engine/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var engine = await _context.Engines
                .FirstOrDefaultAsync(m => m.EngineId == id);
            if (engine == null)
            {
                return NotFound();
            }

            return View(engine);
        }

        // POST: Engine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var engine = await _context.Engines.FindAsync(id);
            _context.Engines.Remove(engine);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EngineExists(int id)
        {
            return _context.Engines.Any(e => e.EngineId == id);
        }
    }
}

Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarRent.Data;
using CarRent.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarRent.Controllers
{
    public class OfficeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OfficeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Office
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Offices.Include(o => o.Address);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Office/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressTitle");
            return View();
        }

        // POST: Office/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OfficeId,OfficeName,OfficePhone,OfficeEmailAddress,AddressId")] Office office)
        {
            if (ModelState.IsValid)
            {
                _context.Add(office);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ListAdmin));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressTitle", office.AddressId);
            return View(office);
        }

        // GET: Office/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var office = await _context.Offices.FindAsync(id);
            if (office == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressTitle", office.AddressId);
            return View(office);
        }

        // POST: Office/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OfficeId,OfficeName,OfficePhone,OfficeEmailAddress,AddressId")] Office office)
        {
            if (id != office.OfficeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(office);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfficeExists(office.OfficeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ListAdmin));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressTitle", office.AddressId);
            return View(office);
        }

        // GET: Office/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var office = await _context.Offices
                .Include(o => o.Address)
                .FirstOrDefaultAsync(m => m.OfficeId == id);
            if (office == null)
            {
                return NotFound();
            }

            return View(office);
        }

        // POST: Office/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var office = await _context.Offices.FindAsync(id);
            _context.Offices.Remove(office);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ListAdmin));
        }

        private bool OfficeExists(int id)
        {
            return _context.Offices.Any(e => e.OfficeId == id);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ListAdmin()
        {
            var applicationDbContext = _context.Offices.Include(o => o.Address);
            return View(await applicationDbContext.ToListAsync());
        }
    }
}

Views/Car/Create.cshtml
@model CarRent.Models.Car

@{
    ViewData["Title"] = Localizer["Add A Car"];
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px" id="contact-section">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="ListAdmin" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="row">
            <div class="col-lg-8 mb-5">
                <form asp-action="Create" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <div class="col-md-4 mb-4 mb-lg-0">
                            <label asp-for="CarBrand" class="control-label"></label>
                            <input asp-for="CarBrand" class="form-control" />
                            <span asp-validation-for="CarBrand" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarModel" class="control-label"></label>
                            <input asp-for="CarModel" class="form-control" />
                            <span asp-validation-for="CarModel" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarType" class="control-label"></label>
                            <select asp-for="CarType" class="form-control" asp-items="@Html.GetEnumSelectList<CarType>()"></select>
                            <span asp-validation-for="CarType" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarTrimPackage" class="control-label"></label>
                            <input asp-for="CarTrimPackage" class="form-control" />
                            <span asp-validation-for="CarTrimPackage" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarColor" class="control-label"></label>
                            <input asp-for="CarColor" class="form-control" />
                            <span asp-validation-for="CarColor" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="EngineId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Engine" class="btn btn-primary float-right">@Localizer["Add a new engine"]</a>
                            <select asp-for="EngineId" class="form-control" asp-items="ViewBag.EngineId"></select>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarTransmissionType" class="control-label"></label>
                            <select asp-for="CarTransmissionType" class="form-control" asp-items="@Html.GetEnumSelectList<CarTransmissionType>()"></select>
                            <span asp-validation-for="CarTransmissionType" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4 mb-4 mb-lg-0">
                            <label asp-for="CarKilometer" class="control-label"></label>
                            <input asp-for="CarKilometer" class="form-control" />
                            <span asp-validation-for="CarKilometer" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarProductYear" class="control-label"></label>
                            <input asp-for="CarProductYear" class="form-control" />
                            <span asp-validation-for="CarProductYear" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="MinimumAge" class="control-label"></label>
                            <input asp-for="MinimumAge" class="form-control" />
                            <span asp-validation-for="MinimumAge" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarRentPrice" class="control-label"></label>
                            <input asp-for="CarRentPrice" class="form-control" />
                            <span asp-validation-for="CarRentPrice" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarDepositPrice" class="control-label"></label>
                            <input asp-for="CarDepositPrice" class="form-control" />
                            <span asp-validation-for="CarDepositPrice" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label asp-for="OfficeId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Office" class="btn btn-primary float-right">@Localizer["Add a new office"]</a>
                            <select asp-for="OfficeId" class="form-control" asp-items="ViewBag.OfficeId"></select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-6">
                            <label asp-for="CarImageUrl" class="control-label"></label>
                            <input type="file" asp-for="CarImageUrl" class="form-control" name="files"/>
                            <span asp-validation-for="CarImageUrl" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarCoverImageUrl" class="control-label"></label>
                            <input type="file" asp-for="CarCoverImageUrl" class="form-control" name="files"/>
                            <span asp-validation-for="CarCoverImageUrl" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mr-auto">
                            <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5" value="@Localizer["Add"]">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Car/Delete.cshtml
@model CarRent.Models.Car

@{
    ViewData["Title"] = Localizer["Delete The Car"];
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@Localizer["Delete"] @Model.CarBrand @Model.CarModel</h2>
                <h3>@Localizer["Are you sure you want to delete this?"]</h3>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="ListAdmin" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="item-1">
                <img src="@Model.CarImageUrl" alt="Car" class="img-fluid">
                <div class="item-1-contents">
                    <div class="text-center">
                        <h3>@Model.CarBrand @Model.CarModel</h3>
                    </div>
                    <ul class="specs">
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.Office.OfficeName)</span>
                            <span class="spec spec2">@Model.Office.OfficeName</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarId)</span>
                            <span class="spec spec2">@Model.CarId</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarType)</span>
                            <span class="spec spec2">@Model.CarType</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.Engine.EngineName)</span>
                            <span class="spec spec2">@Model.Engine.EngineName</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarTransmissionType)</span>
                            <span class="spec spec2">@Model.CarTransmissionType</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarTrimPackage)</span>
                            <span class="spec spec2">@Model.CarTrimPackage</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarColor)</span>
                            <span class="spec spec2">@Model.CarColor</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarKilometer)</span>
                            <span class="spec spec2">@Model.CarKilometer</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarProductYear)</span>
                            <span class="spec spec2">@Model.CarProductYear</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarRentPrice)</span>
                            <span class="spec spec2">@Model.CarRentPrice</span>
                        </li>
                        <li>
                            <span class="spec2">@Html.DisplayNameFor(model => model.CarDepositPrice)</span>
                            <span class="spec spec2">@Model.CarDepositPrice</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="CarId" />
            <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
        </form>
    </div>
</div>

Views/Car/Edit.cshtml
@model CarRent.Models.Car

@{
    ViewData["Title"] = Localizer["Edit The Car"];
}

<div class="padding-top-120px bg-dark"></div>

<div class="site-section bg-light padding-top-120px" id="contact-section">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="d-flex action mb-5">
            <a asp-action="ListAdmin" class="btn btn-primary">@Localizer["Go back to list"]</a>
        </div>
        <div class="row">
            <div class="col-lg-8 mb-5">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="CarId" />
                    <div class="form-group row">
                        <div class="col-md-4 mb-4 mb-lg-0">
                            <label asp-for="CarBrand" class="control-label"></label>
                            <input asp-for="CarBrand" class="form-control" />
                            <span asp-validation-for="CarBrand" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarModel" class="control-label"></label>
                            <input asp-for="CarModel" class="form-control" />
                            <span asp-validation-for="CarModel" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarType" class="control-label"></label>
                            <select asp-for="CarType" class="form-control" asp-items="@Html.GetEnumSelectList<CarType>()"></select>
                            <span asp-validation-for="CarType" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarTrimPackage" class="control-label"></label>
                            <input asp-for="CarTrimPackage" class="form-control" />
                            <span asp-validation-for="CarTrimPackage" class="text-danger"></span>
                        </div>
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarColor" class="control-label"></label>
                            <input asp-for="CarColor" class="form-control" />
                            <span asp-validation-for="CarColor" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="EngineId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Engine" class="btn btn-primary float-right">@Localizer["Add a new engine"]</a>
                            <select asp-for="EngineId" class="form-control" asp-items="ViewBag.EngineId"></select>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarTransmissionType" class="control-label"></label>
                            <select asp-for="CarTransmissionType" class="form-control" asp-items="@Html.GetEnumSelectList<CarTransmissionType>()"></select>
                            <span asp-validation-for="CarTransmissionType" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4 mb-4 mb-lg-0">
                            <label asp-for="CarKilometer" class="control-label"></label>
                            <input asp-for="CarKilometer" class="form-control" />
                            <span asp-validation-for="CarKilometer" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="CarProductYear" class="control-label"></label>
                            <input asp-for="CarProductYear" class="form-control" />
                            <span asp-validation-for="CarProductYear" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label asp-for="MinimumAge" class="control-label"></label>
                            <input asp-for="MinimumAge" class="form-control" />
                            <span asp-validation-for="MinimumAge" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-4 mb-lg-0">
                            <label asp-for="CarRentPrice" class="control-label"></label>
                            <input asp-for="CarRentPrice" class="form-control" />
                            <span asp-validation-for="CarRentPrice" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarDepositPrice" class="control-label"></label>
                            <input asp-for="CarDepositPrice" class="form-control" />
                            <span asp-validation-for="CarDepositPrice" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label asp-for="OfficeId" class="control-label"></label>
                            <a asp-action="Create" asp-controller="Office" class="btn btn-primary float-right">@Localizer["Add a new office"]</a>
                            <select asp-for="OfficeId" class="form-control" asp-items="ViewBag.OfficeId"></select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-6">
                            <label asp-for="CarImageUrl" class="control-label"></label>
                            <input type="file" asp-for="CarImageUrl" class="form-control" name="files" />
                            <span asp-validation-for="CarImageUrl" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="CarCoverImageUrl" class="control-label"></label>
                            <input type="file" asp-for="CarCoverImageUrl" class="form-control" name="files"/>
                            <span asp-validation-for="CarCoverImageUrl" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mr-auto">
                            <input type="submit" class="btn btn-block btn-primary text-white py-3 px-5" value="@Localizer["Update"]">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}